---
title: "Clase_RNAseq_Doctorado"
author: "Carlos Villarroel"
date: "3 de diciembre de 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(tidyr)
library(DESeq2)
library(tximport)
library(clusterProfiler)
library(org.Sc.sgd.db)
library(stringr)
library(ggplot2)
library(pheatmap)
```

```{r}

samples <- list.files(full.names = T, pattern="salmon$")

files <- file.path(samples, "quant.sf")

names(files) <- str_replace(samples, "./", "") %>% str_replace(".salmon", "")
```

```{r}
txi <- tximport(files, type="salmon", countsFromAbundance="lengthScaledTPM",txOut = T)
```

```{r}
data <- txi$counts %>% round() %>% data.frame()

sampletype <- factor(c(rep("control",2), rep("treatment", 2)))
meta <- data.frame(sampletype, row.names = colnames(txi$counts))
```
```{r}
ggplot(data)+ geom_histogram(aes(x = W1), stat = "bin", bins = 200) + xlab("Raw expression counts")+ylab("Number of genes")

```
```{r}

dds <- DESeqDataSetFromMatrix(data, colData = meta, design = ~sampletype)
```
```{r}
mean_counts <- apply(data[,1:2], 1, mean)        #The second argument '1' of 'apply' function indicates the function being applied to rows. Use '2' if applied to columns 
variance_counts <- apply(data[,1:2], 1, var)
df <- data.frame(mean_counts, variance_counts)

ggplot(df) +
  geom_point(aes(x=mean_counts, y=variance_counts)) + 
  scale_y_log10(limits = c(1,1e9)) +
  scale_x_log10(limits = c(1,1e9)) +
  geom_abline(intercept = 0, slope = 1, color="red")
```

```{r}
dds <- DESeq(dds)

```

```{r}
head(counts(dds))

```
```{r}
par(mfrow=c(1,2))
boxplot(log2(counts(dds, normalized=FALSE)+1), main="Raw counts", col=rep(c("lightblue","lightgreen"), each=2), ylim = c(0, 15),las=2)

boxplot(log2(counts(dds, normalized=TRUE)+1), main="Normalized counts", col=rep(c("lightblue","lightgreen"), each=2), ylim = c(0, 15),las=2)
```
```{r}
rld <- rlog(dds, blind=FALSE)
plotPCA(rld, intgroup=c("sampletype"))

```

```{r}
res <- results(dds)
sum(res$padj < 0.05, na.rm=TRUE) #display number of genes with an adjusted p value less than .05
plotMA(res,ylim=c(-2,2),alpha=0.05,main="MA-plot raw values")


```

```{r}
DEGSUP<-which(res$padj<0.05&res$log2FoldChange > 0.5)
DEGSDOWN<-which(res$padj<0.05&res$log2FoldChange < -0.5)
pheatmap(assay(rld)[DEGSUP,], cluster_rows=TRUE, show_rownames=TRUE, cluster_cols=FALSE,scale = "row",fontsize_row = 4,main="Hierarchical cluster",border_color = NA)
```

```{r}
allgenes<-rownames(data)
upgenes<-rownames(data)[DEGSUP]
ego <- enrichGO(gene = upgenes, 
                 universe = allgenes,
                 keyType = "ENSEMBL",
                 OrgDb = org.Sc.sgd.db, 
                 ont = "BP", 
                 pAdjustMethod = "BH", 
                 qvalueCutoff = 0.05, 
                 readable = F, minGSSize = 5)
dotplot(ego, showCategory=10)
```

